server:
  port: 8082

grpc:
  server:
    enabled: ${GRPC_SERVER_ENABLED:true}
    port: ${GRPC_PORT:9092}

spring:
  profiles:
    active: local
  config:
    import: optional:file:.env[.properties]
